// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCem1oxo29jQMKlLh0CDmrZlLD_3kI-00A',
    appId: '1:85797971993:android:3d2a2d9da723498722e288',
    messagingSenderId: '85797971993',
    projectId: 'testdartbasics',
    storageBucket: 'testdartbasics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0H_E9dthrsk_eb7yLl83EhJg3_k5szk4',
    appId: '1:85797971993:ios:c68e6c0e984211d622e288',
    messagingSenderId: '85797971993',
    projectId: 'testdartbasics',
    storageBucket: 'testdartbasics.appspot.com',
    iosBundleId: 'com.example.dartbasics',
  );

}
